

export class TransactionsInquiry {
    constructor(
        public arn: string,
        public processingDate: string,
        public batchNo: number,
        public seqNo: number,
        public cardName: string,
        public tranDesc: string,
        public tranDateTime: string,
        public authOnly: string,
        public authDateTime: string,
        public settledAmount: number,
        public dispensedAmount: number,
        public cashBackAmount: number,
        public surchargeAmount: number,
        public originalAuthAmount: number,
        public totalAuthAmount: number,
        public completeCode: number,
        public pan: string,
        public expirationDate: string,
        public authNetwork: number,
        public authCode: string,
        public authType: string,
        public authRespCode: string,
        public authSourceCode: string,
        public visaTranRefNo: string,
        public avsResponseCode: string,
        public commTypeDesc: string,
        public captureTypeDesc: string,
        public posEntryModeDesc: string,
        public tieredQualificationType: number,
        public cardQualificationType: number,
        public grossTranAmount: number,
        public grossTranAmountPaid: number,
        public paidDate: string,
        public achOriginDate: string,
        public bankRTNbr: string,
        public bankAcctType: number,
        public bankAcctNbr: string,
        public tieredDesc: string,
        public tranType: number,
        public termID: string,
        public cardPaymentDate: string,
        public cardType: number,
        public errorCode: string,
        public reasonCD1: string,
        public cardQualDesc: string,
        public externalID: string,
        public networkRefNbr: string,
        public rtcIndicator: string,
        public decryptData: string,
        public cvmDescription: string,
        public netID: string,
        public fullDeviceID: string
    ) {

    }
        
    }