using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Worldpay.CIS.DataAccess.Product;
using Wp.CIS.LynkSystems.Model.Administrative;
using Wp.CIS.LynkSystems.Model.Enums;

namespace CIS.WebApi.UnitTests.Administrative.Product
{
    public class MockProductRepository : IProductRepository
    {

        #region Private Fields

        private List<ProductModel> _productList = null;

        #endregion

        #region Public Constructors

        public MockProductRepository()
        {
            this._productList = new List<ProductModel>
            {
                new ProductModel()
                {
                    ProductCode = 1,
                    ATMBalanceMethodID = 2,
                    BalanceMethodDesc = "Balance Method 3",
                    BrandId = 4,
                    BusinessType = 5,
                    CheckReaderDescription = "Reader Desc 6",
                    CheckReaderID = 7,
                    CheckReaderName = "Reader Name 8",
                    Description = "Description 9",
                    DirectDebitOnly = false,
                    DLTypeID = 10,
                    DownloadTime = "Download time 11",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 12,
                    InstallType = 13,
                    Integrated = false,
                    IntegratedPinPad = 14,
                    IntegratedPrinter = true,
                    IsInVAMS = 15,
                    IsMobile = 16,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 17",
                    MfgCode = "MfgCode 18",
                    ObsoleteIndicator = false,
                    OverallCount = 19,
                    PCIReport = true,
                    PinPadType = "pin pad type 19",
                    PrinterDescription = "printer description 20",
                    PrinterID = 21,
                    PrinterName = "printer name 22",
                    ProductType = "printer type 23",
                    ProductTypeID = 24,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 25",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 26",
                    TerminalCategory = "terminal category",
                    TerminalDescription = "terminal description 27",
                    TerminalManufCode = "terminal manuf code 28",
                    TerminalSort = 29,
                    TerminalType = "terminal type 30",
                    ThirdPartyProductName = "third party product name 31",
                    TSYSAutoUpdate = 32,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 33,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 34,
                    ATMBalanceMethodID = 35,
                    BalanceMethodDesc = "Balance Method 36",
                    BrandId = 37,
                    BusinessType = 38,
                    CheckReaderDescription = "Reader Desc 39",
                    CheckReaderID = 40,
                    CheckReaderName = "Reader Name 41",
                    Description = "Description 42",
                    DirectDebitOnly = false,
                    DLTypeID = 43,
                    DownloadTime = "Download time 44",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 45,
                    InstallType = 46,
                    Integrated = false,
                    IntegratedPinPad = 47,
                    IntegratedPrinter = true,
                    IsInVAMS = 48,
                    IsMobile = 49,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 50",
                    MfgCode = "MfgCode 51",
                    ObsoleteIndicator = false,
                    OverallCount = 52,
                    PCIReport = true,
                    PinPadType = "pin pad type 53",
                    PrinterDescription = "printer description 54",
                    PrinterID = 55,
                    PrinterName = "printer name 56",
                    ProductType = "printer type 57",
                    ProductTypeID = 58,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 59",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 60",
                    TerminalCategory = "terminal category 61",
                    TerminalDescription = "terminal description 62",
                    TerminalManufCode = "terminal manuf code 63",
                    TerminalSort = 64,
                    TerminalType = "terminal type 65",
                    ThirdPartyProductName = "third party product name 66",
                    TSYSAutoUpdate = 67,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 68,
                    Wireless = true
                },

                new ProductModel()
                {
                    ProductCode = 70,
                    ATMBalanceMethodID = 71,
                    BalanceMethodDesc = "Balance Method 72",
                    BrandId = 73,
                    BusinessType = 74,
                    CheckReaderDescription = "Reader Desc 75",
                    CheckReaderID = 76,
                    CheckReaderName = "Reader Name 77",
                    Description = "Description 78",
                    DirectDebitOnly = false,
                    DLTypeID = 79,
                    DownloadTime = "Download time 80",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 81,
                    InstallType = 82,
                    Integrated = false,
                    IntegratedPinPad = 83,
                    IntegratedPrinter = true,
                    IsInVAMS = 84,
                    IsMobile = 85,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 86",
                    MfgCode = "MfgCode 87",
                    ObsoleteIndicator = false,
                    OverallCount = 88,
                    PCIReport = true,
                    PinPadType = "pin pad type 89",
                    PrinterDescription = "printer description 90",
                    PrinterID = 91,
                    PrinterName = "printer name 92",
                    ProductType = "printer type 93",
                    ProductTypeID = 94,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 95",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 96",
                    TerminalCategory = "terminal category 97",
                    TerminalDescription = "terminal description 98",
                    TerminalManufCode = "terminal manuf code 99",
                    TerminalSort = 100,
                    TerminalType = "terminal type 101",
                    ThirdPartyProductName = "third party product name 102",
                    TSYSAutoUpdate = 104,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 104,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 200,
                    ATMBalanceMethodID = 201,
                    BalanceMethodDesc = "Balance Method 202",
                    BrandId = 203,
                    BusinessType = 204,
                    CheckReaderDescription = "Reader Desc 205",
                    CheckReaderID = 206,
                    CheckReaderName = "Reader Name 207",
                    Description = "Description 208",
                    DirectDebitOnly = false,
                    DLTypeID = 209,
                    DownloadTime = "Download time 210",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 211,
                    InstallType = 212,
                    Integrated = false,
                    IntegratedPinPad = 213,
                    IntegratedPrinter = true,
                    IsInVAMS = 214,
                    IsMobile = 215,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 216",
                    MfgCode = "MfgCode 217",
                    ObsoleteIndicator = false,
                    OverallCount = 218,
                    PCIReport = true,
                    PinPadType = "pin pad type 219",
                    PrinterDescription = "printer description 220",
                    PrinterID = 221,
                    PrinterName = "printer name 222",
                    ProductType = "printer type 223",
                    ProductTypeID = 224,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 225",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 226",
                    TerminalCategory = "terminal category 227",
                    TerminalDescription = "terminal description 228",
                    TerminalManufCode = "terminal manuf code 229",
                    TerminalSort = 230,
                    TerminalType = "terminal type 231",
                    ThirdPartyProductName = "third party product name 232",
                    TSYSAutoUpdate = 233,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 234,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 300,
                    ATMBalanceMethodID = 301,
                    BalanceMethodDesc = "Balance Method 302",
                    BrandId = 303,
                    BusinessType = 304,
                    CheckReaderDescription = "Reader Desc 305",
                    CheckReaderID = 306,
                    CheckReaderName = "Reader Name 307",
                    Description = "Description 308",
                    DirectDebitOnly = false,
                    DLTypeID = 309,
                    DownloadTime = "Download time 310",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 311,
                    InstallType = 312,
                    Integrated = false,
                    IntegratedPinPad = 313,
                    IntegratedPrinter = true,
                    IsInVAMS = 314,
                    IsMobile = 315,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 316",
                    MfgCode = "MfgCode 317",
                    ObsoleteIndicator = false,
                    OverallCount = 318,
                    PCIReport = true,
                    PinPadType = "pin pad type 319",
                    PrinterDescription = "printer description 320",
                    PrinterID = 321,
                    PrinterName = "printer name 322",
                    ProductType = "printer type 323",
                    ProductTypeID = 324,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 325",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 326",
                    TerminalCategory = "terminal category 327",
                    TerminalDescription = "terminal description 328",
                    TerminalManufCode = "terminal manuf code 329",
                    TerminalSort = 330,
                    TerminalType = "terminal type 331",
                    ThirdPartyProductName = "third party product name 332",
                    TSYSAutoUpdate = 333,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 334,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 400,
                    ATMBalanceMethodID = 401,
                    BalanceMethodDesc = "Balance Method 202",
                    BrandId = 403,
                    BusinessType = 404,
                    CheckReaderDescription = "Reader Desc 405",
                    CheckReaderID = 406,
                    CheckReaderName = "Reader Name 407",
                    Description = "Description 408",
                    DirectDebitOnly = false,
                    DLTypeID = 409,
                    DownloadTime = "Download time 410",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 411,
                    InstallType = 412,
                    Integrated = false,
                    IntegratedPinPad = 413,
                    IntegratedPrinter = true,
                    IsInVAMS = 414,
                    IsMobile = 415,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 416",
                    MfgCode = "MfgCode 417",
                    ObsoleteIndicator = false,
                    OverallCount = 418,
                    PCIReport = true,
                    PinPadType = "pin pad type 419",
                    PrinterDescription = "printer description 420",
                    PrinterID = 421,
                    PrinterName = "printer name 422",
                    ProductType = "printer type 423",
                    ProductTypeID = 424,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 425",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 426",
                    TerminalCategory = "terminal category 427",
                    TerminalDescription = "terminal description 428",
                    TerminalManufCode = "terminal manuf code 429",
                    TerminalSort = 430,
                    TerminalType = "terminal type 431",
                    ThirdPartyProductName = "third party product name 432",
                    TSYSAutoUpdate = 433,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 434,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 500,
                    ATMBalanceMethodID = 501,
                    BalanceMethodDesc = "Balance Method 502",
                    BrandId = 503,
                    BusinessType = 504,
                    CheckReaderDescription = "Reader Desc 505",
                    CheckReaderID = 506,
                    CheckReaderName = "Reader Name 507",
                    Description = "Description 508",
                    DirectDebitOnly = false,
                    DLTypeID = 509,
                    DownloadTime = "Download time 510",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 511,
                    InstallType = 512,
                    Integrated = false,
                    IntegratedPinPad = 513,
                    IntegratedPrinter = true,
                    IsInVAMS = 514,
                    IsMobile = 515,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 516",
                    MfgCode = "MfgCode 517",
                    ObsoleteIndicator = false,
                    OverallCount = 518,
                    PCIReport = true,
                    PinPadType = "pin pad type 519",
                    PrinterDescription = "printer description 520",
                    PrinterID = 521,
                    PrinterName = "printer name 522",
                    ProductType = "printer type 523",
                    ProductTypeID = 524,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 525",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 526",
                    TerminalCategory = "terminal category 527",
                    TerminalDescription = "terminal description 528",
                    TerminalManufCode = "terminal manuf code 529",
                    TerminalSort = 530,
                    TerminalType = "terminal type 531",
                    ThirdPartyProductName = "third party product name 532",
                    TSYSAutoUpdate = 533,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 534,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 600,
                    ATMBalanceMethodID = 601,
                    BalanceMethodDesc = "Balance Method 602",
                    BrandId = 603,
                    BusinessType = 604,
                    CheckReaderDescription = "Reader Desc 605",
                    CheckReaderID = 606,
                    CheckReaderName = "Reader Name 607",
                    Description = "Description 608",
                    DirectDebitOnly = false,
                    DLTypeID = 609,
                    DownloadTime = "Download time 610",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 611,
                    InstallType = 612,
                    Integrated = false,
                    IntegratedPinPad = 613,
                    IntegratedPrinter = true,
                    IsInVAMS = 614,
                    IsMobile = 615,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 616",
                    MfgCode = "MfgCode 617",
                    ObsoleteIndicator = false,
                    OverallCount = 618,
                    PCIReport = true,
                    PinPadType = "pin pad type 619",
                    PrinterDescription = "printer description 620",
                    PrinterID = 621,
                    PrinterName = "printer name 622",
                    ProductType = "printer type 623",
                    ProductTypeID = 624,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 625",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 626",
                    TerminalCategory = "terminal category 627",
                    TerminalDescription = "terminal description 628",
                    TerminalManufCode = "terminal manuf code 629",
                    TerminalSort = 630,
                    TerminalType = "terminal type 631",
                    ThirdPartyProductName = "third party product name 632",
                    TSYSAutoUpdate = 633,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 634,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 700,
                    ATMBalanceMethodID = 701,
                    BalanceMethodDesc = "Balance Method 702",
                    BrandId = 703,
                    BusinessType = 704,
                    CheckReaderDescription = "Reader Desc 207",
                    CheckReaderID = 706,
                    CheckReaderName = "Reader Name 707",
                    Description = "Description 708",
                    DirectDebitOnly = false,
                    DLTypeID = 709,
                    DownloadTime = "Download time 710",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 711,
                    InstallType = 712,
                    Integrated = false,
                    IntegratedPinPad = 713,
                    IntegratedPrinter = true,
                    IsInVAMS = 714,
                    IsMobile = 715,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 716",
                    MfgCode = "MfgCode 717",
                    ObsoleteIndicator = false,
                    OverallCount = 718,
                    PCIReport = true,
                    PinPadType = "pin pad type 719",
                    PrinterDescription = "printer description 720",
                    PrinterID = 721,
                    PrinterName = "printer name 722",
                    ProductType = "printer type 723",
                    ProductTypeID = 724,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 725",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 726",
                    TerminalCategory = "terminal category 727",
                    TerminalDescription = "terminal description 728",
                    TerminalManufCode = "terminal manuf code 729",
                    TerminalSort = 730,
                    TerminalType = "terminal type 731",
                    ThirdPartyProductName = "third party product name 732",
                    TSYSAutoUpdate = 733,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 734,
                    Wireless = true
                },
                new ProductModel()
                {
                    ProductCode = 800,
                    ATMBalanceMethodID = 801,
                    BalanceMethodDesc = "Balance Method 802",
                    BrandId = 803,
                    BusinessType = 804,
                    CheckReaderDescription = "Reader Desc 805",
                    CheckReaderID = 806,
                    CheckReaderName = "Reader Name 807",
                    Description = "Description 808",
                    DirectDebitOnly = false,
                    DLTypeID = 809,
                    DownloadTime = "Download time 810",
                    E2EEEnabled = true,
                    EPSEnabled = false,
                    GLOnlyTerminal = true,
                    HIDEnabled = 811,
                    InstallType = 812,
                    Integrated = false,
                    IntegratedPinPad = 813,
                    IntegratedPrinter = true,
                    IsInVAMS = 814,
                    IsMobile = 815,
                    IsPinlessDebit = false,
                    IsSmallMerchant = true,
                    isSupports24MID = false,
                    IsTSYSEquip = true,
                    Manufacturer = "Manufacturer 816",
                    MfgCode = "MfgCode 817",
                    ObsoleteIndicator = false,
                    OverallCount = 818,
                    PCIReport = true,
                    PinPadType = "pin pad type 819",
                    PrinterDescription = "printer description 820",
                    PrinterID = 821,
                    PrinterName = "printer name 822",
                    ProductType = "printer type 823",
                    ProductTypeID = 824,
                    SupportE2EE = false,
                    SupporteWIC = true,
                    SupportLevel = "support level 825",
                    SupportsDeposits = false,
                    SupportsDirectDebit = true,
                    TemplateFileName = "template file name 826",
                    TerminalCategory = "terminal category 827",
                    TerminalDescription = "terminal description 828",
                    TerminalManufCode = "terminal manuf code 829",
                    TerminalSort = 830,
                    TerminalType = "terminal type 831",
                    ThirdPartyProductName = "third party product name 832",
                    TSYSAutoUpdate = 833,
                    UsedEquipment = false,
                    UserVarTemplate = true,
                    VARTerminal = false,
                    VTMajorVersion = 834,
                    Wireless = true
                }
            };
        }

        #endregion

        #region IProductRepository Implementation

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IEnumerable<ProductModel>> GetAllProductsAsync()
        {
            return await Task.Run(() =>
            {
                return _productList;
            });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="description"></param>
        /// <returns></returns>
        public async Task<IEnumerable<ProductModel>> GetProductsByDescriptionAsync(string description)
        {
            return await Task.Run(() =>
            {
                return _productList;
            });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="firstRecordNumber"></param>
        /// <param name="pageSize"></param>
        /// <param name="sortField"></param>
        /// <param name="sortOrder"></param>
        /// <returns></returns>
        public async Task<IEnumerable<ProductModel>> GetProductsWithPagingAsync(int firstRecordNumber, int pageSize, string sortField, SortOrderEnum sortOrder)
        {
            return await Task.Run(() =>
            {
                var response = this._productList
                                    .Skip(firstRecordNumber)
                                    .Take(pageSize)
                                    .ToList();

                return response;
            });
        }

        #endregion
    }
}
