//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wp.CIS.LynkSystems.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controllers_EPSMappingController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_EPSMappingController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wp.CIS.LynkSystems.WebApi.Resources.Controllers.EPSMappingController", typeof(Controllers_EPSMappingController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while inserting Mappings.
        /// </summary>
        public static string EPSMappingAllErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingAllErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while copying Mappings.
        /// </summary>
        public static string EPSMappingCopyErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingCopyErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Begin and end dates are mandatory.
        /// </summary>
        public static string EPSMappingDatesErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingDatesErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParamName is mandatory.
        /// </summary>
        public static string EPSMappingParamNameErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingParamNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while retrieving Mappings.
        /// </summary>
        public static string EPSMappingRetrieveErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingRetrieveErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldpay Table/Field name are mandatory.
        /// </summary>
        public static string EPSMappingTable_FieldNamerErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingTable_FieldNamerErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating Mappings.
        /// </summary>
        public static string EPSMappingUpdateErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingUpdateErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viper fields are mandatory.
        /// </summary>
        public static string EPSMappingViperFieldsErrorMsg {
            get {
                return ResourceManager.GetString("EPSMappingViperFieldsErrorMsg", resourceCulture);
            }
        }
    }
}
