//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wp.CIS.LynkSystems.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controllers_EPSTableController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_EPSTableController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wp.CIS.LynkSystems.WebApi.Resources.Controllers.EPSTableController", typeof(Controllers_EPSTableController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultXML provided when Definitiononly checked.
        /// </summary>
        internal static string EPSTableDefaultXMLErrorMsg {
            get {
                return ResourceManager.GetString("EPSTableDefaultXMLErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDate not provided.
        /// </summary>
        internal static string EPSTableEffectiveDateErrorMsg {
            get {
                return ResourceManager.GetString("EPSTableEffectiveDateErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while retrieving Petro tables.
        /// </summary>
        internal static string EPSTableGetAllPetroTableErrorMsg {
            get {
                return ResourceManager.GetString("EPSTableGetAllPetroTableErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastUpdatedBy not provided.
        /// </summary>
        internal static string EPSTableLastUpdatedByErrorMsg {
            get {
                return ResourceManager.GetString("EPSTableLastUpdatedByErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName not provided.
        /// </summary>
        internal static string EPSTableTableNameErrorMsg {
            get {
                return ResourceManager.GetString("EPSTableTableNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while upserting Petro tables.
        /// </summary>
        internal static string EPSTableUpsertErrorMsg {
            get {
                return ResourceManager.GetString("EPSTableUpsertErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version not provided.
        /// </summary>
        internal static string EPSTableVersionErrorMsg {
            get {
                return ResourceManager.GetString("EPSTableVersionErrorMsg", resourceCulture);
            }
        }
    }
}
